"""Add ip_address to Alert

Revision ID: c2e0a8d5e54b
Revises: bac3e81ef744
Create Date: 2025-07-04 01:00:29.835122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2e0a8d5e54b'
down_revision = 'bac3e81ef744'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.String(length=45), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###
